version: "3"
services:
  web:
     build:
       context: .
     command: gunicorn conscious_sweater.wsgi:application --bind 0.0.0.0:8001
     ports:
       - "8001:8001"
     env_file:
       - ./.env
     depends_on:
         - db
  db:
     image: postgres:12.0-alpine
     volumes:
             - ./postgres/data/:/var/lib/postgresql/data/
     env_file:
             - ./.env.db