version: '3.3'

services:
  web:
    build: .
    command: python manage.py runserver
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

