# Generated by Django 3.1 on 2020-08-20 09:12

from django.db import migrations, models
import django.db.models.deletion
import map.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('adress', models.CharField(max_length=300)),
                ('shop_domain', models.CharField(max_length=200)),
                ('opennig_hours', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('categories', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='marker_category',
            fields=[
                ('marker_type', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('marker_image', models.FileField(upload_to='pins/')),
            ],
            options={
                'verbose_name_plural': 'Marker Categories',
            },
        ),
        migrations.CreateModel(
            name='marker_shop_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_image', models.FileField(upload_to=map.models.get_shop_name_upload_to)),
                ('shop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='map.marker')),
            ],
        ),
        migrations.AddField(
            model_name='marker',
            name='marker',
            field=models.ForeignKey(default='sustanible', on_delete=django.db.models.deletion.SET_DEFAULT, to='map.marker_category'),
        ),
    ]
