# Generated by Django 3.1 on 2020-08-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('adress', models.CharField(max_length=300)),
                ('shop_domain', models.CharField(max_length=200)),
                ('opennig_hours', models.CharField(blank=True, default='', max_length=200)),
                ('categories', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='correct_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('adress', models.CharField(max_length=300)),
                ('shop_domain', models.CharField(max_length=200)),
                ('opennig_hours', models.CharField(blank=True, default='', max_length=200)),
                ('categories', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
